### ISSUE TITLE
Map-Based Unit Types

### ISSUE THREAD

**Issue by KHunter-Arma** [ARandy-BADPMC/Bad-Company-Operation-Chainbreaker#13]
- Turn insurgency unit types lists into functions with many lists of different factions' units, where it automatically selects which lists to use depending on what map is running.

- Possibly integrate the lists with OPCB so the tasks also feed from the same lists.

**Comment by AlexKBADPMC** [comment]
I just noticed, that this is already implemented. We're still missing some of the major maps, but every map, that we've been to, has it's own units already. Closing this one.

**Comment by AlexKBADPMC** [comment]
I just noticed, that this is already implemented. We're still missing some of the major maps, but every map, that we've been to, has it's own units already. Closing this one.
