### ISSUE TITLE
"Minefield" task gets ruined by AI vehicles

### ISSUE THREAD

**Issue by KHunter-Arma** [ARandy-BADPMC/Bad-Company-Operation-Chainbreaker#32]
Ever since random patrols and civilian vehicles were added in to the mix, the "minefield" task has become a laughing matter of waiting for it to complete itself so we can get free money. Find a solution to this.

**Comment by AlexKBADPMC** [comment]
Minefield main-task was removed and minefield sidemission was reworked. Closing this one.
